seed: 42

data:
  validation_size: 10000

noise:
  type: gaussian
  standard_deviation: 0.3

model:
  first_filters: 32
  second_filters: 32
  kernel_size: 3

training:
  batch_size: 128
  maximum_epochs: 20